name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Exporta credenciais e variável AWS_REGION
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1   # <- região, não AZ

      # 2. Login no ECR (sem inputs extras)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build e push (tag já apontando pro seu registry do ECR)
      - name: Build & push image
        env:
          REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-app
          IMAGE_TAG:  ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push    $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # 4. Deploy na EC2 via SSH
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST:        ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > key && chmod 600 key
          ssh -o StrictHostKeyChecking=no -i key $USER@$HOST <<'EOF'
            cd /path/to/your/app
            git pull origin main
            docker compose pull
            docker compose up -d --build
          EOF
