name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST <<EOF
          cd /path/to/your/app
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
        EOF
env:
  PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.EC2_HOST }}
  DB_URL: ${{ secrets.DB_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}