name: Deploy to AWS EC2 with Docker Compose

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        env:
          REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: juscash
          IMAGE_TAG:  ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push    $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST:        ${{ secrets.EC2_HOST }}   
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' > key
          chmod 600 key

          ssh -o StrictHostKeyChecking=no -i key $USER@$HOST <<'EOF'
            set -e 
            APP_DIR=/home/ubuntu/juscash  
            cd "$APP_DIR"
            git pull origin main
            docker-compose build
            docker-compose up -d
          EOF

